sudo: false
language: python
python:
- 3.6
install:
- pip install -U pip wheel
- pip install -r requirements.txt -e "$TRAVIS_BUILD_DIR"
services:
- mysql
before_script:
- mysql -e 'CREATE DATABASE IF NOT EXISTS Publications;'
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  - "$HOME/.cache/pip"
script:
- pytest -v
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_3df81cd2614d_key -iv $encrypted_3df81cd2614d_iv
  -in .travis/secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
