sudo: false
language: python
python:
  - 3.6
install: pip install -r requirements.txt
before-script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/robopubs/robopubs.py"
  - export FLASK_DEBUG=1

script:
  pytest -v