"""Added initial publication table

Revision ID: b3507c55a6fc
Revises: 
Create Date: 2018-05-15 23:26:49.764133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3507c55a6fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abstract'),
    sa.UniqueConstraint('title')
    )
    op.drop_index('abstract', table_name='publication1')
    op.drop_index('title', table_name='publication1')
    op.drop_table('publication1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication1',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('abstract', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('title', 'publication1', ['title'], unique=True)
    op.create_index('abstract', 'publication1', ['abstract'], unique=True)
    op.drop_table('publication')
    # ### end Alembic commands ###
